name: um-version-validator
version: 1.0.0
title: Um Version Validator
description: Validates the version of a UM
author: https://github.com/thanyalukj
requirements: []
configuration:
  properties:
    pattern:
      type: string
  additionalProperties: false
