#!/bin/bash
set -euo pipefail

PATTERN="$BUILDKITE_PLUGIN_UM_VERSION_VALIDATOR_PATTERN"

echo "--- :1234: Counting the number of files"

COUNT=$(find . -name "$PATTERN" | wc -l)

echo "Found ${COUNT} files matching ${PATTERN}"

buildkite-agent annotate "Found ${COUNT} files matching ${PATTERN}"
